-- Run this in the Supabase SQL Editor AFTER the existing application schema.
ALTER TABLE trusted_channels ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled'));
ALTER TABLE trusted_channels ADD COLUMN IF NOT EXISTS youtube_channel_id TEXT;
ALTER TABLE trusted_channels ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE trusted_channels ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE TABLE IF NOT EXISTS blacklisted_videos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id TEXT NOT NULL UNIQUE, reason TEXT,
  blacklisted_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS content_flags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id TEXT NOT NULL, topic_id INTEGER REFERENCES curriculum_topics(id) ON DELETE SET NULL,
  flagged_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL, reason TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open','dismissed','resolved')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), resolved_at TIMESTAMPTZ
);
ALTER TABLE topic_challenges ADD COLUMN IF NOT EXISTS review_status VARCHAR(20) NOT NULL DEFAULT 'ok' CHECK (review_status IN ('ok','flagged'));
ALTER TABLE topic_quizzes ADD COLUMN IF NOT EXISTS review_status VARCHAR(20) NOT NULL DEFAULT 'ok' CHECK (review_status IN ('ok','flagged'));
CREATE INDEX IF NOT EXISTS idx_topic_videos_video_id ON topic_videos(video_id);
CREATE INDEX IF NOT EXISTS idx_content_flags_status ON content_flags(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_topic_videos_topic_id ON topic_videos(topic_id);
